version: "3"
services:
  api:
   build: 
     context: ./
     dockerfile: dockerfile-api
   ports:
   - "4455:4455"
  proxy:
   build:
     context: ./
     dockerfile: dockerfile-proxy
   ports:
   - "4456:4456"   